name: Riverland
version: 1.3
main: riverland.dev.riverland.Riverland
depend: [WorldGuard, Sentinel, Citizens]
softdepend: [Factions, SilkSpawners]
api-version: 1.13
author: riverland.dev
commands:
  AdminHelp:
    description: Creates a Ticket, and sends it to server admins for review.
    permission: Riverland.AdminHelp
    permission-message: You do not have permission!
    usage: /<command> [msg]
  OPAdminHelp:
    description: Access OP Tools for AdminHelp
    permission: Riverland.OpAdminHelp
    permission-message: You do not have permission!
    usage: /<command> [Display|Remove|RemoveAll]
  Riverland:
    description: Access OP Tools for AdminHelp
    permission: Riverland.Riverland
    permission-message: You do not have permission!
    usage: /<command> [Reload|TNTSmall|TNTMedium|TNTLarge|Pickup|CustomTNT1|CustomTNT2|CustomTNT3]
  Thrall:
    description: Commands NPC's
    permission: Riverland.Thrall
    permission-message: You do not have permission!
    usage: /Thrall [Follow|Follow PlayerName|Wait|Equip|Strip]

permissions:
  Riverland.AdminHelp:
    description: Allows AdminHelp command
    default: true
  Riverland.Thrall:
    description: Allows AdminHelp command
    default: true
  Riverland.OpAdminHelp:
    description: Allows OPAdminHelp command
    default: op
  Riverland.Riverland:
    description: Riverland plugin management
    default: op